language: es

pipeline:
  - name: SpacyNLP
    model: es_core_news_sm
  - name: SpacyTokenizer
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "rasa/LaBSE"
  - name: RegexFeaturizer
  - name: extractors.ita_entity_extractor.ITAEntityExtractor
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 40
    evaluate_on_number_of_examples: 0
    evaluate_every_number_of_epochs: 20
  - name: FallbackClassifier
    threshold: 0.5

policies:

  - name: RulePolicy
    core_fallback_action_name: action_fallback_ita



